version: 2.1

jobs:
  build:
    docker:
      - image: alpine/docker-with-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker version
          apk add make
          make build-push CI_NAME=circleci

workflows:
  build:
    jobs:
      - build:
          name: build

  nightly:
    triggers:
       - schedule:
           cron: "0 2 * * 0"
           filters:
             branches:
               only:
                 - master
                 - main
    jobs:
      - build:
          name: build
          filters:
            branches:
              only:
                - master
                - main
